---
#
# Ansible managed
#
repository:
  description: Configure timezine settings
  homepage: https://mullholland.net
  topics: cloud, database, development, monitoring, networking, system, ansible, molecule, tox, playbook
